version = 1
SPDX-PackageName = "kleopatra"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/kleopatra"

[[annotations]]
path = ["README.packagers", "tests/gpg-connect-agent-scripts/**", "tests/gnupg_home/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
